### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Archiolidius** [sindresorhus/remote-git-tags#1]
Hi!
When i run "npm install --save remote-git-tags" i get:

Error: Bad Request
npm ERR!     at errorResponse (/usr/lib/node_modules/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

Have you any idea what happened?

**Comment by Archiolidius** [comment]
when i install "remote-git-tags" like dependency in package.json it installing sucsess, but when i try include lib to file I get errors in console: http://pix.toile-libre.org/upload/original/1430921618.png

**Comment by kevva** [comment]
> npm ERR! If you need help, you may report this entire log,
> npm ERR! including the npm and node versions, at:
> npm ERR! http://github.com/npm/npm/issues

And for the second issue, are you trying to load it in the browser?

**Comment by Archiolidius** [comment]
@kevva Yes, I am trying to load it in the browser.

**Comment by kevva** [comment]
Well, that's not going to work. Even if you build it with browserify, this module makes use of some native node modules which browserify wouldn't be able to build.

**Comment by Archiolidius** [comment]
@kevva Hmm.. therefore I can use this library only with node.js, right? And no way to use it the in browser?

**Comment by kevva** [comment]
Exactly.

**Comment by Archiolidius** [comment]
Ok, thank you!

**Comment by kevva** [comment]
@Archiolidius, never mind. Browserify **does** in fact support native modules, so you are able to use this if you build it first. See https://github.com/substack/node-browserify for instructions on how to use it.

**Comment by sindresorhus** [comment]
This might work in the browser, as it's only JS, but not sure if the underlying transports work.
