### ISSUE TITLE
How could I connect to private git repository?

### ISSUE THREAD

**Issue by Archiolidius** [sindresorhus/remote-git-tags#2]
Is it possible to connect to private gitlab repository?

**Comment by sindresorhus** [comment]
No idea. Try. It works with any git repo, but haven't tried private ones yet.

**Comment by kevva** [comment]
Doesn't seem to work for me at least.

**Comment by sindresorhus** [comment]
What kind of URL did you use SSH or HTTPS?

**Comment by kevva** [comment]
HTTPS. Can try SSH too.

edit: Same result.
