### ISSUE TITLE
Not working with private repo

### ISSUE THREAD

**Issue by victorbadila** [sindresorhus/remote-git-tags#5]
I have a private repo in Bitbucket which I can clone locally due to having a ssh key. Doesn't seem to work with this module though. No errors are shown, it simply hangs forever when I call it with my private git url.

```
const tags = await remoteGitTags(privateRepositoryPath);
console.log(tags);
```

**Comment by sindresorhus** [comment]
v3 now uses the `git` binary instead, so this should no longer be an issue: https://github.com/sindresorhus/remote-git-tags/releases/tag/v3.0.0
